export const UPDATE_COMPANYNAME = "UPDATE_COMPANYNAME";
export const UPDATE_INVOICENAME = "UPDATE_INVOICENAME";
export const UPDATE_CURRENCY = "UPDATE_CURRENCY";
export const ADD_ITEMS = "ADD_ITEMS";
export const REMOVE_ITEMS = "REMOVE_ITEMS";
export const EDIT_ITEMS = "EDIT_ITEMS";
